import "./AboutUs.css";

export default function About() {
  return (
    <div className="aboutUsContent">
      <h6 className="aboutMainTitle">ABOUT</h6>
      <h6 className="aboutTitle">STORE CONCEPT</h6>
      <p>
        UNIFORM DISPLAY IS A MENSWEAR SHOWROOM FOCUSED ON THE UNIQUE DESIGN
        ELEMENTS OF VINTAGE CLOTHING. OUR TEAM EMPHASIZES SOURCING GARMENTS THAT
        SHOW SIGNS OF AGING AND WEAR. WE LIKE TO SHOWCASE CLOTHES THAT OTHERS
        WOULD SEE AS IMPERFECT OR, IN SOME CASES, UNWEARABLE. WE TAKE PRIDE IN
        SELLING GARMENTS WITH THESE CHARACTERISTICS.
      </p>
      <h6 className="aboutTitle">SHIPPING</h6>
      <p>
        ALL DOMESTIC ORDERS ARE SHIPPED VIA USPS PRIORITY MAIL, INTERNATIONAL
        ORDERS ARE SHIPPED VIA DHL EXPRESS INTERNATIONAL. ORDERS ARE PROCESSED
        WITHIN 1-3 BUSINESS DAYS. WE DO OUR BEST TO SEND OUT ALL ORDERS IN A
        TIMELY MANNER. ONCE AN ORDER HAS BEEN PROCESSED, IT CAN NOT BE MODIFIED
        OR CANCELED. INTERNATIONAL CUSTOMERS MAY BE SUBJECT TO DUTIES AND FEES,
        WHICH ARE OUT OF OUR CONTROL. UNFORTUNATELY, WE CAN NOT COVER THESE
        FEE'S AND HAVE NO WAY OF CALCULATING THE CHARGE BEFORE YOUR ORDER IS
        PLACED. THESE FEES WILL BE LEVIED TO YOU UPON ARRIVAL OF YOUR ORDER.
        PLEASE CHECK WITH YOUR LOCAL CUSTOMS OFFICE TO DETERMINE WHAT THESE
        ADDITIONAL COSTS WILL BE PRIOR TO YOUR PURCHASE. WE ARE NOT LIABLE FOR
        ANY PACKAGES THAT ARE LOST OR STOLEN DURING SHIPMENT. WE DO NOT SHIP ON
        WEEKENDS OR HOLIDAYS.
      </p>
      <h6 className="aboutTitle">RETURNS</h6>
      <p>
        ALL SALES ARE FINAL, NO REFUNDS, RETURNS, OR EXCHANGES ARE PERMITTED. IN
        THE RARE CIRCUMSTANCE THAT YOU RECEIVE AN INCORRECT ITEM, WE CAN PROVIDE
        YOU WITH STORE CREDIT FOR THE TOTAL AMOUNT SPENT. PLEASE SEND US AN
        INQUIRY WITHIN A TIMELY MANNER TO: CARLITOSVIANO@GMAIL.COM.
      </p>
      </div>
  );
}
